// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Navigation
 * ```
 *       ░▒▓▓▒░      ░▒▓▓
 *   ░▒▓▓▓▒██▒▓▓▓▒▒▓▓▓▒██
 *   ██▒░  ██  ░▒██▒░  ██
 *   ██    ██    ██    ██
 *   ██    ██    ██    ██
 *   ██    ██    ██    ██
 *   ██    ██    ██    ██
 *   ██    ██    ██    ██
 *   ██  ░▒██▒░  ██  ░▒██
 *   ██▒▓▓▓▒▒▓▓▓▒██▒▓▓▓▒░
 *   ▓▓▒░      ░▒▓▓▒░
 * ```
 */
export const IconNavigationMap = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Navigation Map'
            width={pickedProps.size || '1rem'}
            height={pickedProps.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M15 6V21M15 6L21 3V18L15 21M15 6L9 3M15 21L9 18M9 18L3 21V6L9 3M9 18V3'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
