// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Edit
 * ```
 *            ░░
 *         ░▒▓▓▓▓▒░
 *      ░▒▓█▓▒  ░▓█▓▒░
 *    ▒▓▓▓▒░      ░▒▓█▓▒
 *   ▓██▒            ▒██▓
 *    ░▒▓▓▒░      ░▒▓▓▒░
 *   ▒▓▒░░▒█▓▒░░▒▓▓▒░░▒▓▒
 *    ▒▓█▓▒░▒▓██▓▒░▒▓█▓▒
 *      ░▒▓█▓▒░░▒▓▓▓▒░
 *         ░▒▓▓▓▓▒░
 *            ░░
 * ```
 */
export const IconLayer = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Layer'
            width={pickedProps.size || '1rem'}
            height={pickedProps.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M21 14L12 20L3 14M21 10L12 16L3 10L12 4L21 10Z'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
