// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Edit
 * ```
 *   ▒▒      ▒▒
 *   ██      ██
 *   ██      ██    ░▒▒▒
 *   ██      ██   ▒▓▓██
 *   ██████████      ██
 *   ██      ██      ██
 *   ██      ██      ██
 *   ██      ██      ██
 *   ▒▒      ▒▒      ▒▒
 * ```
 */
export const IconHeadingH1 = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Heading H1'
            width={pickedProps.size || '1rem'}
            height={pickedProps.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M16 10L19 9L19 19M3 5V12M3 12V19M3 12H11M11 5V12M11 12V19'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
