// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Edit
 * ```
 *                 ░▓▓░
 *    ▒▓▓▓▓▓▓▒   ░▓████▓░
 *    ░░░░░░░░   ▒▓░██░▓▒
 *                  ██
 *    ▒█████████▒   ██
 *                  ▒▒
 *    ░░░░░░░░░░░░░░
 *    ▒▓▓▓▓▓▓▓▓▓▓▓▓▒
 * ```
 */
export const IconSortDescending = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Sort Descending'
            width={pickedProps.size || '1rem'}
            height={pickedProps.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M4 17H16M4 12H13M4 7H10M18 13V5M18 5L21 8M18 5L15 8'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
