// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Edit
 * ```
 *            ░▒▓▓▓▓▒░
 *          ░▓█▒░░░░▒█▓░
 *        ░▓█▓░░▒▓▓▓░░██
 *      ░▒█▓░░▒█▓░▒█▓ ▒█░
 *     ▒█▓░ ▒█▓░░▒█▓░░██
 *    ░▓▒ ▒█▓▒ ▒█▓▒ ▒█▓░
 *      ░▓█▒ ▒▓█▒ ▒▓█▒
 *     ▒█▒ ░▓█▒░░▓█▒
 *     ██   ▒░░▓█▒░
 *     ▒█▓░░░▓█▓░
 *      ░▒▓▓▓▒░
 * ```
 */
export const IconEditPaperclipAttechmentTilt = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Edit Paperclip Attechment Tilt'
            width={pickedProps.size || '1rem'}
            height={pickedProps.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M4.53564 11.4647L11.4299 4.5704C13.4802 2.52015 16.8044 2.52015 18.8546 4.5704C20.9049 6.62066 20.9046 9.94496 18.8544 11.9952L10.8994 19.9502C9.53258 21.317 7.31688 21.3168 5.95004 19.95C4.58321 18.5831 4.58287 16.3673 5.94971 15.0005L13.9047 7.0455C14.5881 6.36208 15.6967 6.36208 16.3801 7.0455C17.0635 7.72892 17.0631 8.83669 16.3796 9.52011L9.48535 16.4144'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
