// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Edit
 * ```
 *      ▓▓▓▓▓▓▓▓▓▓▓▓▓▓
 *      ▒▒░░░░██░░░░▒▒
 *            ██
 *            ██
 *            ██
 *            ██
 *            ██
 *          ░░██░░
 *          ▒▓▓▓▓▒
 * ```
 */
export const IconText = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Text'
            width={pickedProps.size || '1rem'}
            height={pickedProps.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M10 19H12M12 19H14M12 19V5M12 5H6V6M12 5H18V6'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
