// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps, type VoidComponent } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Calendar
 * ```
 *          ▒▒▒▒▒▒
 *          ▒▒▒▒▒▒   ░░
 *        ░▒▒▓▓▓▓▒▒░ ▒█▓░
 *      ░▓█▓▒░░░░▒▓█▓░░▒▒
 *     ▒█▓░        ░▓█▒
 *    ▒█▒            ▒█▒
 *    ██   ▒▒▒▒▒▒▒▒   ██
 *    ██   ▒▒▒▒▒▒▒▒   ██
 *    ▒█▒            ▒█▒
 *     ▒█▒░        ░▒█▒
 *      ▒▓█▓▒░░░░▒▓█▓░
 *        ░▒▒▓▓▓▓▒▒░
 * ```
 */
export const IconCalendarTimerRemove: VoidComponent<IconProps> = (props) => {
    const [local, others] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Calendar Timer Remove'
            width={local.size || '1rem'}
            height={local.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...others}
        >
            <path
                d='M9 13H15M21 6L19 4M10 2H14M12 21C7.58172 21 4 17.4183 4 13C4 8.58172 7.58172 5 12 5C16.4183 5 20 8.58172 20 13C20 17.4183 16.4183 21 12 21Z'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
