// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps, type VoidComponent } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Edit
 * ```
 *   ▒▒      ▒▒
 *   ██      ██
 *   ██      ██   ░▒▒▒▒░
 *   ██      ██  ▒█▓▒▒▓█▒
 *   ██████████  ██   ░██
 *   ██      ██  ░░  ░▓█░
 *   ██      ██    ░▓█▒
 *   ██      ██  ░▓██▒░░░
 *   ▒▒      ▒▒  ▒▓▓▓▓▓▓▒
 * ```
 */
export const IconEditHeadingH2: VoidComponent<IconProps> = (props) => {
    const [local, others] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Edit Heading H2'
            width={local.size || '1rem'}
            height={local.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...others}
        >
            <path
                d='M15 12.5V12C15 10.3431 16.3431 9 18 9H18.1716C19.7337 9 20.9996 10.2665 20.9996 11.8286C20.9996 12.5788 20.702 13.2982 20.1716 13.8286L15 19.0002L21 19M3 5V12M3 12V19M3 12H11M11 5V12M11 12V19'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
