// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Edit
 * ```
 *    ▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒
 *   ▓█▒░░░░░░░░░░░░░░▒█▓
 *   ██                ▓▓
 *   ▒█▒▒▒▒▒▒▒▒
 *    ░▒▒▒▒▒▒▒▒
 *              ▒▓▓▓▓▓▓▒
 *              ░░░░░░░░
 * ```
 */
export const IconEditDeleteRow = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Edit Delete Row'
            width={pickedProps.size || '1rem'}
            height={pickedProps.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M14 16H20M21 10V9C21 7.89543 20.1046 7 19 7H5C3.89543 7 3 7.89543 3 9V11C3 12.1046 3.89543 13 5 13H11'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
