// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Edit
 * ```
 *    ░░░░░░░░░░░░░░░░░░
 *    ▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒
 *    ▒████████████████▒
 *    ▒████████████████▒
 *    ▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒
 *    ░░░░░░░░░░░░░░░░░░
 * ```
 */
export const IconEditTextAlignJustify = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Edit Text Align Justify'
            width={pickedProps.size || '1rem'}
            height={pickedProps.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M20 18H4M20 14H4M20 10H4M20 6H4'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
