// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps, type VoidComponent } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Edit
 * ```
 *       ░▓▒
 *    ▒▒▒█▓░ ▒▓▓▓▓▓▓▓▓▓▒
 *    ░▒▓▒░  ░░░░░░░░░░░
 *       ▒█▓
 *    ▓▓▓█▒  ▒█████████▒
 *     ░▒░░░
 *    ░░░▒█▒ ░░░░░░░░░░░
 *    ▒██▓░  ▒▓▓▓▓▓▓▓▓▓▒
 *      ░
 * ```
 */
export const IconEditListChecklist: VoidComponent<IconProps> = (props) => {
    const [local, others] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Edit List Checklist'
            width={local.size || '1rem'}
            height={local.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...others}
        >
            <path
                d='M11 17H20M8 15L5.5 18L4 17M11 12H20M8 10L5.5 13L4 12M11 7H20M8 5L5.5 8L4 7'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
