// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps, type VoidComponent } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Edit
 * ```
 *            ▒▓▓▓▓▒
 *            ░▒█▒░░
 *             ██
 *            ▒█▒
 *            ██
 *           ▒█▒
 *           ██
 *        ░░▒█▒░
 *        ▒▓▓▓▓▒
 * ```
 */
export const IconEditItalic: VoidComponent<IconProps> = (props) => {
    const [local, others] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Edit Italic'
            width={local.size || '1rem'}
            height={local.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...others}
        >
            <path
                d='M8 19H10M10 19H12M10 19L14 5M12 5H14M14 5H16'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
