// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Arrow
 * ```
 *                 ▓▓
 *                 ██
 *                 ██
 *                 ██
 *           ▒▒    ██
 *         ▒██▒    ██
 *       ░▓█▒      ██
 *      ▓███▓▓▓▓▓▓▓▓▒
 *      ░▒██▒░░░░░░
 *        ░▓█▒░
 *          ░▓▒
 * ```
 */
export const IconArrowArrowSubDownLeft = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Arrow Arrow Sub Down Left'
            width={pickedProps.size || '1rem'}
            height={pickedProps.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M11 11L6 16M6 16L11 21M6 16H13.8031C14.921 16 15.4802 16 15.9076 15.7822C16.2839 15.5905 16.5905 15.2839 16.7822 14.9076C17 14.4802 17 13.921 17 12.8031V3'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
