// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps, type VoidComponent } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Arrow
 * ```
 *        ▒▒     ░▓▓░
 *        ██   ░▓████▓░
 *        ██   ▒▓░██░▓▒
 *        ██      ██
 *        ██      ██
 *        ██      ██
 *     ▒▓░██░▓▒   ██
 *     ░▓████▓░   ██
 *       ░▓▓░     ▒▒
 * ```
 */
export const IconArrowDownUp: VoidComponent<IconProps> = (props) => {
    const [local, others] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Arrow Down Up'
            width={local.size || '1rem'}
            height={local.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...others}
        >
            <path
                d='M11 16L8 19M8 19L5 16M8 19V5M13 8L16 5M16 5L19 8M16 5V19'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
