// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps, type VoidComponent } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Arrow
 * ```
 *             ▒▓░
 *             ░▒█▓░
 *         ░░░░░░▒██▒░
 *       ▒▓▓▓▓▓▓▓▓███▓
 *       ██      ▒█▓░
 *       ██    ▒██▒
 *       ██    ▒▒
 *       ██
 *       ██
 *       ██
 *       ▓▓
 * ```
 */
export const IconArrowSubUpRight: VoidComponent<IconProps> = (props) => {
    const [local, others] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Arrow Sub Up Right'
            width={local.size || '1rem'}
            height={local.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...others}
        >
            <path
                d='M13 13L18 8M18 8L13 3M18 8H10.2002C9.08009 8 8.51962 8 8.0918 8.21799C7.71547 8.40973 7.40973 8.71547 7.21799 9.0918C7 9.51962 7 10.0801 7 11.2002V21.0002'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
