// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps, type VoidComponent } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Arrow
 * ```
 *        ░▒▓▓▓▓▓▓▒░
 *      ▒█▓▒▒░░░░▒▒▓█▒
 *    ░██▒          ▒██░
 *   ░█▓   ▒▒░        ▓█░
 *   ▓█░   ▒▓█▒  ▒▒   ░█▓
 *   ██      ▒▓▓▒██    ██
 *   ▓█░     ░▒████   ░█▓
 *   ░█▓     ▒▓▒▒▒▒   ▓█░
 *    ░██▒          ▒██░
 *      ▒█▓▒▒░░░░▒▒▓█▒
 *        ░▒▓▓▓▓▓▓▒░
 * ```
 */
export const IconArrowCircleDownRight: VoidComponent<IconProps> = (props) => {
    const [local, others] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Arrow Circle Down Right'
            width={local.size || '1rem'}
            height={local.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...others}
        >
            <path
                d='M11 15H15M15 15V11M15 15L9 9M21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21C16.9706 21 21 16.9706 21 12Z'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
