// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps, type VoidComponent } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Arrow
 * ```
 *      ░▓▒
 *    ░▒█▓░
 *   ▒███▓▒▓▓▓▓▓▓▓▓▒▒▒
 *   ▒▓██▒▒▒▒▒▒▒▒▒▒▒▒▓█▒
 *     ▒▓▓▒           ▒█▒
 *       ▒▒            ██
 *                    ▒█▒
 *           ░░░░░░░▒▓█▒
 *           ▒▓▓▓▓▓▓▓▒░
 * ```
 */
export const IconArrowUndoUpLeft: VoidComponent<IconProps> = (props) => {
    const [local, others] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Arrow Undo Up Left'
            width={local.size || '1rem'}
            height={local.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...others}
        >
            <path
                d='M7 13L3 9M3 9L7 5M3 9H16C18.7614 9 21 11.2386 21 14C21 16.7614 18.7614 19 16 19H11'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
