// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps, type VoidComponent } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Arrow
 * ```
 *           ░▒▒▒▒▒▒▒▒
 *           ░▒▒▒▒▓███░
 *               ▒█▓▓█░
 *             ▒█▓▒ ▒█░
 *           ▒██▒   ▒█░
 *         ░▓█▒     ░▒
 *       ░▓█▒░
 *      ▓█▓░
 *      ▒░
 * ```
 */
export const IconArrowUpRightLg: VoidComponent<IconProps> = (props) => {
    const [local, others] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Arrow Up Right Lg'
            width={local.size || '1rem'}
            height={local.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...others}
        >
            <path
                d='M18.3646 5.63623H11.2939M18.3646 5.63623L18.3643 12.7073M18.3646 5.63623L5.63672 18.3642'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
