// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps, type VoidComponent } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Arrow
 * ```
 *           ░░    ░░
 *         ░▒█▓  ░▒█▓
 *        ▒█▓▒  ▒█▓▒
 *       ▓█▓   ▓█▓
 *        ▒█▓▒  ▒█▓▒
 *         ░▒█▓  ░▒█▓
 *           ░░    ░░
 * ```
 */
export const IconArrowChevronLeftDuo: VoidComponent<IconProps> = (props) => {
    const [local, others] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Arrow Chevron Left Duo'
            width={local.size || '1rem'}
            height={local.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...others}
        >
            <path
                d='M17 16L13 12L17 8M11 16L7 12L11 8'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
