// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps, type VoidComponent } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Warning
 * ```
 *        ░▒▓▓▓▓▓▓▒░
 *      ▒▓▓▒▒░░░░▒▒▓█▒
 *    ░███▓░        ▒██░
 *   ░█▓ ░▓█▒░        ▓█░
 *   ▓█░   ░▓█▒       ░█▓
 *   ██      ▒██▒      ██
 *   ▓█░       ▒█▓▒   ░█▓
 *   ░█▓        ░▒█▓░░▓█░
 *    ░██▒        ░▓███░
 *      ▒█▓▒▒░░░░▒▒▓▓▒
 *        ░▒▓▓▓▓▓▓▒░
 * ```
 */
export const IconWarningStopSign: VoidComponent<IconProps> = (props) => {
    const [local, others] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Warning Stop Sign'
            width={local.size || '1rem'}
            height={local.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...others}
        >
            <path
                d='M5.75 5.75L18.25 18.25M12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12C21 16.9706 16.9706 21 12 21Z'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
