// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Warning
 * ```
 *        ░▒▓▓▓▓▓▓▒░
 *      ▒█▓▒▒░░░░▒▒▓█▒
 *    ░██▒          ▒██░
 *   ░█▓      ▓▓      ▓█░
 *   ▓█░      ██      ░█▓
 *   ██       ██       ██
 *   ▓█░      ░░      ░█▓
 *   ░█▓      ▒▒      ▓█░
 *    ░██▒          ▒██░
 *      ▒█▓▒▒░░░░▒▒▓█▒
 *        ░▒▓▓▓▓▓▓▒░
 * ```
 */
export const IconCircleWarning = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Circle Warning'
            width={pickedProps.size || '1rem'}
            height={pickedProps.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M12 8.4502V12.4502M12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12C21 16.9706 16.9706 21 12 21ZM12.0498 15.4502V15.5502L11.9502 15.5498V15.4502H12.0498Z'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
