// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * System
 * ```
 *         ▒▒▓▓▓▓▒▒
 *       ▒█▓▒░░░░▒▓█▒
 *      ▒█▒   ▒▒   ▓█▒
 *      ██    ██    ██
 *      ██    ▓▓    ██
 *      ██          ██
 *      ██          ██
 *      ██          ██
 *      ▒█▓        ▓█▒
 *       ▒█▓▒░░░░▒██▒
 *         ▒▒▓▓▓▓▒▒
 * ```
 */
export const IconSystemMouse = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='System Mouse'
            width={pickedProps.size || '1rem'}
            height={pickedProps.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M12 10V7M18 9V15C18 18.3137 15.3137 21 12 21C8.68629 21 6 18.3137 6 15V9C6 5.68629 8.68629 3 12 3C15.3137 3 18 5.68629 18 9Z'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
