// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * System
 * ```
 *         ░░░░░░░░
 *       ▒▓▓▓▓▓▓▓▓▓▓▒
 *      ▓█▒        ▒█▓
 *      ██▓▒░░░░░░▒▓██
 *      ██▒▒▓▓▓▓▓▓▒▒██
 *      ██          ██
 *      ██          ██
 *      ██          ██
 *      ▓█▒░      ░▒█▓
 *       ▒▓▓▓▓▓▓▓▓▓▓▒
 *          ░░░░░░
 * ```
 */
export const IconCylinder = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Cylinder'
            width={pickedProps.size || '1rem'}
            height={pickedProps.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M18 7V17C18 18.6569 15.3137 20 12 20C8.68629 20 6 18.6569 6 17V7M18 7C18 5.34315 15.3137 4 12 4C8.68629 4 6 5.34315 6 7M18 7C18 8.65685 15.3137 10 12 10C8.68629 10 6 8.65685 6 7'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
