// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * File
 * ```
 *         ░▒▓▓▓▓▒▒░
 *       ▒█▓▒▒░░░▒▓█▒
 *    ▒▒▓█▒   ▒▒   ▒█▓░
 *  ▒█▓▒▒░    ██    ░█▓▒░
 * ▒█▒     ▒▒ ██ ▒▒  ▒▒▓█▓
 * ██      ▒▓████▓▒     ░█▓
 * ▓█▒       ░▒▒░       ░██
 *  ▒█▓▒░░░░░░░░░░░░░░░▒█▓░
 *   ░▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒
 * ```
 */
export const IconFileCloudDownload = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='File Cloud Download'
            width={pickedProps.size || '1rem'}
            height={pickedProps.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M12 9V15M12 15L15 13M12 15L9 13M23 15C23 12.7909 21.2091 11 19 11C18.9764 11 18.9532 11.0002 18.9297 11.0006C18.4447 7.60802 15.5267 5 12 5C9.20335 5 6.79019 6.64004 5.66895 9.01082C3.06206 9.18144 1 11.3498 1 13.9999C1 16.7613 3.23858 19.0001 6 19.0001L19 19C21.2091 19 23 17.2091 23 15Z'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
