// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Environment
 * ```
 *            ░░
 *            ██
 *     ▒▓░    ▒▒    ░▒▓
 *     ░▓▓░░▒▒▓▓▒▒░ ▓▓░
 *       ░▒█▓▒░░▒▓█▒
 *       ▒█▒      ▒█▒
 *  ▒██▒ ██        ██ ▒██▒
 *       ▒█▒      ▒█▒
 *        ▒█▓▒░░▒▓█▒
 *     ░▒▓░░▒▒▓▓▒▒░ ▓▓░
 *     ▒▓░    ▒▒    ░▓▓
 *            ██
 *            ░░
 * ```
 */
export const IconSun = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Sun'
            width={pickedProps.size || '1rem'}
            height={pickedProps.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M12 4V2M12 20V22M6.41421 6.41421L5 5M17.728 17.728L19.1422 19.1422M4 12H2M20 12H22M17.7285 6.41421L19.1427 5M6.4147 17.728L5.00049 19.1422M12 17C9.23858 17 7 14.7614 7 12C7 9.23858 9.23858 7 12 7C14.7614 7 17 9.23858 17 12C17 14.7614 14.7614 17 12 17Z'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
