// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Arrow
 * ```
 *        ░▒▓▓▓▓▓▓▒░
 *      ▒█▓▒▒░░░░▒▒▓█▒
 *    ░██▒          ▒██░
 *   ░█▓   ▒▒▒▒▓▒     ▓█░
 *   ▓█░   ████▒░     ░█▓
 *   ██    ██▒▓▓▒      ██
 *   ▓█░   ▒▒  ▒█▓▒   ░█▓
 *   ░█▓        ░▒▒   ▓█░
 *    ░██▒          ▒██░
 *      ▒█▓▒▒░░░░▒▒▓█▒
 *        ░▒▓▓▓▓▓▓▒░
 * ```
 */
export const IconArrowArrowCircleUpLeft = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Arrow Arrow Circle Up Left'
            width={pickedProps.size || '1rem'}
            height={pickedProps.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M13 9H9M9 9V13M9 9L15 15M21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21C16.9706 21 21 16.9706 21 12Z'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
