// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Arrow
 * ```
 *                ░░
 *              ░▓██▓░
 *            ░▒█▓██▓█▒░
 *           ▒█▓▒ ██ ░▓█▒
 *           ▒▒   ██   ▒▒
 *                ██
 *   ░░░░░░░░░░░░▒█▓
 *   ▒▓▓▓▓▓▓▓▓▓▓▓▓▒
 * ```
 */
export const IconArrowSubRightUp = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Arrow Sub Right Up'
            width={pickedProps.size || '1rem'}
            height={pickedProps.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M11 11L16 6M16 6L21 11M16 6V13.8031C16 14.921 16 15.4802 15.7822 15.9076C15.5905 16.2839 15.2839 16.5905 14.9076 16.7822C14.4802 17 13.921 17 12.8031 17H3'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
