// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Arrow
 * ```
 *       ░░    ░░
 *       ▒█▒░  ▒█▒░
 *        ░▓█▒  ░▓█▒
 *          ▓█▓   ▓█▓
 *        ░▓█▒  ░▓█▒
 *       ▒█▒░  ▒█▒░
 *       ░░    ░░
 * ```
 */
export const IconChevronRightDuo = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Chevron Right Duo'
            width={pickedProps.size || '1rem'}
            height={pickedProps.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M13 8L17 12L13 16M7 8L11 12L7 16'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
