// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Arrow
 * ```
 *           ▒▓▓▓▓▓▓▓▒░
 *           ░░░░░░░▒▓█▒
 *                    ▒█▒
 *       ▒▒            ██
 *     ▒▓▓▒           ▒█▒
 *   ▒▓██▒▒▒▒▒▒▒▒▒▒▒▒▓█▒
 *   ▒███▓▒▓▓▓▓▓▓▓▓▒▒░
 *    ░▒█▓░
 *      ░▓▒
 * ```
 */
export const IconArrowUndoDownLeft = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Arrow Undo Down Left'
            width={pickedProps.size || '1rem'}
            height={pickedProps.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M7 11L3 15M3 15L7 19M3 15H16C18.7614 15 21 12.7614 21 10C21 7.23858 18.7614 5 16 5H11'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
