// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Arrow
 * ```
 *     ░▒▓▓▓▓▓▓▓▒
 *    ▒█▓▒░░░░░░░
 *   ▓█▒
 *   ██            ▒▒
 *   ▒█▒           ▒▓▓▒
 *    ▒█▓▒▒▒▒▒▒▒▒▒▒▒▒██▓▒
 *      ░▒▒▓▓▓▓▓▓▓▓▒▓███▒
 *                 ░▒█▒░
 *                 ▒▓░
 * ```
 */
export const IconArrowArrowUndoDownRight = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Arrow Arrow Undo Down Right'
            width={pickedProps.size || '1rem'}
            height={pickedProps.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M17 11L21 15M21 15L17 19M21 15H8C5.23858 15 3 12.7614 3 10C3 7.23858 5.23858 5 8 5H13'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
