// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Arrow
 * ```
 *      ▒░
 *      ▓█▓░
 *       ░▓█▒░
 *         ░▓█▒     ░▒
 *           ▒██▒   ▒█░
 *             ▒█▓▒ ▒█░
 *               ▒█▓▓█░
 *           ░▒▒▒▒▓███░
 *           ░▒▒▒▒▒▒▒▒
 * ```
 */
export const IconArrowDownRightLg = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Arrow Down Right Lg'
            width={pickedProps.size || '1rem'}
            height={pickedProps.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M18.3637 18.364L18.3633 11.293M18.3637 18.364L11.293 18.3645M18.3637 18.364L5.63574 5.63623'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
