// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Arrow
 * ```
 *       ▒▓▓▓▓▓▓▓▓▒
 *       ████▒░░░░░
 *       ██░▓█▒
 *       ██  ▒██▒
 *       ██    ▒█▓▒
 *       ▒▒     ░▒█▓░
 *                ░▒▒
 * ```
 */
export const IconArrowUpLeftMd = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Arrow Up Left Md'
            width={pickedProps.size || '1rem'}
            height={pickedProps.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M17 17L7 7M7 7V15M7 7H15'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
