// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Communication
 * ```
 *                ░▓▓▓▓░
 *               ▒█▒░░▒█▒
 *              ░██░  ░█▓
 *    ░▒▒▒▒░ ░▒▓▓▓▓█▓▓█▓░
 *   ▒█▓▒▒▓██▓▒░░  ░▒▒░
 *   ██    ██
 *   ▒█▓▒▒▓██▓▒░░  ░▒▒░
 *    ░▒▒▒▒░ ░▒▓▓▓▓█▓▓█▓░
 *              ░██░  ░█▓
 *               ▒█▒░░▒█▒
 *                ░▓▓▓▓░
 * ```
 */
export const IconShareAndroid = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Share Android'
            width={pickedProps.size || '1rem'}
            height={pickedProps.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M9 13.5L15 16.5M15 7.5L9 10.5M18 21C16.3431 21 15 19.6569 15 18C15 16.3431 16.3431 15 18 15C19.6569 15 21 16.3431 21 18C21 19.6569 19.6569 21 18 21ZM6 15C4.34315 15 3 13.6569 3 12C3 10.3431 4.34315 9 6 9C7.65685 9 9 10.3431 9 12C9 13.6569 7.65685 15 6 15ZM18 9C16.3431 9 15 7.65685 15 6C15 4.34315 16.3431 3 18 3C19.6569 3 21 4.34315 21 6C21 7.65685 19.6569 9 18 9Z'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
