// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Interface
 * ```
 *      ░▒▒▓▓▓▓▒▒░
 *    ░▒█▓▒░░░░▒▓█▒░
 *   ░██░   ▒▒   ░██░
 *   ▓█░  ░░██░░  ░█▓
 *   ██  ▒██████▒  ██
 *   ▒█▒    ██    ▒█▒
 *    ▓█▒   ▒▒   ▒█▓
 *     ▒▓▓▒▒░░▒▒▓██▓░
 *       ░▒▒▓▓▒▒░ ░▒█▓░
 *                  ░▓█▒░
 *                    ░▓▒
 * ```
 */
export const IconMagnifyingGlassPlus = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Magnifying Glass Plus'
            width={pickedProps.size || '1rem'}
            height={pickedProps.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M7 10H10M10 10H13M10 10V7M10 10V13M15 15L21 21M10 17C6.13401 17 3 13.866 3 10C3 6.13401 6.13401 3 10 3C13.866 3 17 6.13401 17 10C17 13.866 13.866 17 10 17Z'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
