// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Interface
 * ```
 *    ▒▓▓▓▓░      ░▓▓▓▓░
 *   ▒█▒░░▒█▒    ▒█▒░░▒█▒
 *   ▓█░   ██    ██   ░█▓
 *   ░▓█▓▓▓██▓▓▓▓██▓▓▓█▓░
 *     ░▒▒▒██▒▒▒▒██▒▒▒░
 *         ██    ██
 *     ░▒▒▒██▒▒▒▒██▒▒▒░
 *   ░▓█▓▓▓██▓▓▓▓██▓▓▓█▓░
 *   ▓█░   ██    ██   ░█▓
 *   ▒█▒░░▒█▒    ▒█▒░░▒█▒
 *    ░▓▓▓▓░      ░▓▓▓▓░
 * ```
 */
export const IconCommand = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Command'
            width={pickedProps.size || '1rem'}
            height={pickedProps.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M9 15V18C9 19.6569 7.65685 21 6 21C4.34315 21 3 19.6569 3 18C3 16.3431 4.34315 15 6 15H9ZM9 15H15M9 15V9M15 15V18C15 19.6569 16.3431 21 18 21C19.6569 21 21 19.6569 21 18C21 16.3431 19.6569 15 18 15H15ZM15 15V9M15 9H9M15 9V6C15 4.34315 16.3431 3 18 3C19.6569 3 21 4.34315 21 6C21 7.65685 19.6569 9 18 9H15ZM9 9V6C9 4.34315 7.65685 3 6 3C4.34315 3 3 4.34315 3 6C3 7.65685 4.34315 9 6 9H9Z'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
