// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Interface
 * ```
 *         ░▒▓▓▓▓▒░
 *        ░█▓▒░░▒▓█░
 *        ██      ██
 *        ██  ██  ██
 *        ░░  ██  ░░
 *            ██
 *        ░░  ██  ░░
 *        ██  ██  ██
 *        ██      ██
 *        ░█▓▒░░▒▓█░
 *         ░▒▓▓▓▓▒░
 * ```
 */
export const IconInterfaceLinkVertical = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Interface Link Vertical'
            width={pickedProps.size || '1rem'}
            height={pickedProps.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M12 8V16M16 15V17C16 19.2091 14.2091 21 12 21C9.79086 21 8 19.2091 8 17V15M16 9V7C16 4.79086 14.2091 3 12 3C9.79086 3 8 4.79086 8 7V9'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
