// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps, type VoidComponent } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Navigation
 * ```
 *    ░▒▓▓▓▓▓▒░░      ░░
 *    ██▒░░░▒▒▓▓▓▓▒▒▒▓██
 *    ██        ░▒▒▒▒▒██
 *    ██              ██
 *    ██              ██
 *    ██              ██
 *    ██▒▒▓▒▒▒░       ██
 *    ██▒▒░▒▒▓▓▓▓▒▒░▒▒█▓
 *    ██       ░▒▒▓▓▓▒░
 *    ██
 *    ▓▓
 * ```
 */
export const IconNavigationFlag: VoidComponent<IconProps> = (props) => {
    const [local, others] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Navigation Flag'
            width={local.size || '1rem'}
            height={local.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...others}
        >
            <path
                d='M4 21V15.6871M4 15.6871C9.81818 11.1377 14.1818 20.2363 20 15.6869V4.31347C14.1818 8.86284 9.81818 -0.236103 4 4.31327V15.6871Z'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
