// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps, type VoidComponent } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Menu
 * ```
 *        ░░      ░░
 *        ▒█▒░  ░▒█▓
 *         ░▓█▒▒█▓▒
 *           ▓██▓
 *         ░▓█▒▒█▓▒
 *        ▒█▒░  ░▒█▓
 *        ░░      ░░
 * ```
 */
export const IconMenuCloseSm: VoidComponent<IconProps> = (props) => {
    const [local, others] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Menu Close Sm'
            width={local.size || '1rem'}
            height={local.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...others}
        >
            <path
                d='M16 16L12 12M12 12L8 8M12 12L16 8M12 12L8 16'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
