// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps, type VoidComponent } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Menu
 * ```
 *     ▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒
 *     ░░░░░░░░░░░░░░░░
 *     ▒██████████████▒
 *            ░░░░░░░░░
 *            ▒▓▓▓▓▓▓▓▒
 * ```
 */
export const IconMenuAlt01: VoidComponent<IconProps> = (props) => {
    const [local, others] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Menu Alt01'
            width={local.size || '1rem'}
            height={local.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...others}
        >
            <path
                d='M12 17H19M5 12H19M5 7H19'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
