// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * User
 * ```
 *         ░▒▓▓▓▓▒░
 *        ▓█▒░░░░▒█▓
 *       ▓█░      ░█▓
 *       ██        ██
 *       ▒█▒      ▒█▒
 *        ▒▓▓▒▒▒▒▓▓▒
 *          ░▒▒▒▒░
 *       ░▒▒▓▓▓▓▓▓▒▒░
 *     ▒▓█▓▒▒░░░░▒▒▓█▓▒
 *    ▒█▒░          ░▒█▒
 *    ▓▓              ▓▓
 * ```
 */
export const IconUserUser02 = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='User User02'
            width={pickedProps.size || '1rem'}
            height={pickedProps.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M20 21C20 18.2386 16.4183 16 12 16C7.58172 16 4 18.2386 4 21M12 13C9.23858 13 7 10.7614 7 8C7 5.23858 9.23858 3 12 3C14.7614 3 17 5.23858 17 8C17 10.7614 14.7614 13 12 13Z'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
