// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * User
 * ```
 *   ░▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒░
 *   ▓█░░░░░░░░░░░░░░░░█▓
 *   ██     ░▒▓▓▒░     ██
 *   ██    ▒█▓▒▒▓█▒    ██
 *   ██    ██    ██    ██
 *   ██    ░█▓▒▒▓█░    ██
 *   ██      ▒▒▒▒      ██
 *   ██    ░▒▓▓▓▓▒░    ██
 *   ██   ▓█▒░░░░▒█▓   ██
 *   ▓█░░▓█▒░░░░░░▒█▓░░█▓
 *   ░▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒░
 * ```
 */
export const IconUserSquare = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='User Square'
            width={pickedProps.size || '1rem'}
            height={pickedProps.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M17 21C17 18.2386 14.7614 16 12 16C9.23858 16 7 18.2386 7 21M17 21H17.8031C18.921 21 19.48 21 19.9074 20.7822C20.2837 20.5905 20.5905 20.2837 20.7822 19.9074C21 19.48 21 18.921 21 17.8031V6.19691C21 5.07899 21 4.5192 20.7822 4.0918C20.5905 3.71547 20.2837 3.40973 19.9074 3.21799C19.4796 3 18.9203 3 17.8002 3H6.2002C5.08009 3 4.51962 3 4.0918 3.21799C3.71547 3.40973 3.40973 3.71547 3.21799 4.0918C3 4.51962 3 5.08009 3 6.2002V17.8002C3 18.9203 3 19.4796 3.21799 19.9074C3.40973 20.2837 3.71547 20.5905 4.0918 20.7822C4.5192 21 5.07899 21 6.19691 21H7M17 21H7M12 13C10.3431 13 9 11.6569 9 10C9 8.34315 10.3431 7 12 7C13.6569 7 15 8.34315 15 10C15 11.6569 13.6569 13 12 13Z'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
