// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * User
 * ```
 *       ▒▓▓▓▓▒  ▒▓▓▒
 *     ░▓█▒░░▒█▓░░░▒█▓░
 *     ██     ░██   ░██
 *     ▓█░    ░█▓   ░█▓
 *     ░▓█▓▒▒▓█▓ ▒▒▓█▓
 *       ░▒▒▒▒░  ▒▒▒░
 *     ░▒▒▓▓▓▓▒▒░  ▒▒▒░
 *   ░▓█▓▒░░░░▒▓█▓░░▒▓█▓░
 *   ▓█░        ░█▓   ░█▓
 *   ░░          ░░    ░░
 * ```
 */
export const IconUsers = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Users'
            width={pickedProps.size || '1rem'}
            height={pickedProps.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M21 19.9999C21 18.2583 19.3304 16.7767 17 16.2275M15 20C15 17.7909 12.3137 16 9 16C5.68629 16 3 17.7909 3 20M15 13C17.2091 13 19 11.2091 19 9C19 6.79086 17.2091 5 15 5M9 13C6.79086 13 5 11.2091 5 9C5 6.79086 6.79086 5 9 5C11.2091 5 13 6.79086 13 9C13 11.2091 11.2091 13 9 13Z'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
