// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps, type VoidComponent } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Interface
 * ```
 *    ░░
 *    ▒█▓░
 *     ░▓█▓░     ░░░░░
 *    ▒▓▓▓▓█▒░   ▒▓▓▓▓▓▒
 *   ▒█▒░  ▒██▒      ░▒█▒
 *   ██   ▒▓████▒      ██
 *   ▒█▒░      ▒█▓░   ▒█▒
 *    ▒▓▓▓▓▓▒   ░▒█▓░ ▒▒
 *      ░░░░░     ░▓█▓░
 *                  ░▓█▒
 *                    ░░
 * ```
 */
export const IconInterfaceLinkHorizontalOff: VoidComponent<IconProps> = (props) => {
    const [local, others] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Interface Link Horizontal Off'
            width={local.size || '1rem'}
            height={local.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...others}
        >
            <path
                d='M8 12H12M12 12L8 8M12 12L20 20M15 8H17C19.2091 8 21 9.79086 21 12C21 13.1947 20.4759 14.2671 19.6455 15M9 16H7C4.79086 16 3 14.2091 3 12C3 9.79086 4.79086 8 7 8H8M8 8L4 4'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
