// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps, type VoidComponent } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Interface
 * ```
 *      ░░░░░    ░░░░░
 *    ▒▓▓▓▓▓▒    ▒▓▓▓▓▓▒
 *   ▒█▒░            ░▒█▒
 *   ██   ▒████████▒   ██
 *   ▒█▒░            ░▒█▒
 *    ▒▓▓▓▓▓▒    ▒▓▓▓▓▓▒
 *      ░░░░░    ░░░░░
 * ```
 */
export const IconInterfaceLinkHorizontal: VoidComponent<IconProps> = (props) => {
    const [local, others] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Interface Link Horizontal'
            width={local.size || '1rem'}
            height={local.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...others}
        >
            <path
                d='M8 12H16M15 8H17C19.2091 8 21 9.79086 21 12C21 14.2091 19.2091 16 17 16H15M9 8H7C4.79086 8 3 9.79086 3 12C3 14.2091 4.79086 16 7 16H9'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
