/** biome-ignore-all lint: Auto generate */
/** biome-ignore-all assist/source/organizeImports: Auto generate */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
    async createSnippet(
        payload: CreateSnippetRequest,
    ): Promise<Result<Snippet, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('create_snippet', { payload }),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async createTag(
        payload: CreateTagRequest,
    ): Promise<Result<Tag, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('create_tag', { payload }),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async getImages(): Promise<Result<Image[], CommandError>> {
        try {
            return { status: 'ok', data: await TAURI_INVOKE('get_images') };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async getVideos(): Promise<Result<Video[], CommandError>> {
        try {
            return { status: 'ok', data: await TAURI_INVOKE('get_videos') };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async getAudio(): Promise<Result<Audio[], CommandError>> {
        try {
            return { status: 'ok', data: await TAURI_INVOKE('get_audio') };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async getSnippets(): Promise<Result<Snippet[], CommandError>> {
        try {
            return { status: 'ok', data: await TAURI_INVOKE('get_snippets') };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async getTags(): Promise<Result<Tag[], CommandError>> {
        try {
            return { status: 'ok', data: await TAURI_INVOKE('get_tags') };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async getSettings(): Promise<Result<Setting, CommandError>> {
        try {
            return { status: 'ok', data: await TAURI_INVOKE('get_settings') };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async getGeneralStats(): Promise<Result<GeneralStats, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('get_general_stats'),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async removeTag(id: TagId): Promise<Result<Tag, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('remove_tag', { id }),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async removeDeleteAllData(): Promise<Result<null, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('remove_delete_all_data'),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async removeDeleteAllImages(): Promise<Result<null, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('remove_delete_all_images'),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async removeDeleteAllVideos(): Promise<Result<null, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('remove_delete_all_videos'),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async removeDeleteAllAudio(): Promise<Result<null, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('remove_delete_all_audio'),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async removeDeleteAllSnippets(): Promise<Result<null, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('remove_delete_all_snippets'),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async removeDeleteAllTags(): Promise<Result<null, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('remove_delete_all_tags'),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async removeDeleteImage(
        id: ImageId,
        payload: DeleteRequest,
    ): Promise<Result<Image, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('remove_delete_image', {
                    id,
                    payload,
                }),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async removeDeleteVideo(
        id: VideoId,
        payload: DeleteRequest,
    ): Promise<Result<Video, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('remove_delete_video', {
                    id,
                    payload,
                }),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async removeDeleteAudio(
        id: AudioId,
        payload: DeleteRequest,
    ): Promise<Result<Audio, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('remove_delete_audio', {
                    id,
                    payload,
                }),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async removeDeleteSnippet(
        id: SnippetId,
        payload: DeleteRequest,
    ): Promise<Result<Snippet, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('remove_delete_snippet', {
                    id,
                    payload,
                }),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async updateImage(
        id: ImageId,
        payload: UpdateImageRequest,
    ): Promise<Result<Image, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('update_image', { id, payload }),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async updateRestoreImage(
        id: ImageId,
    ): Promise<Result<Image, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('update_restore_image', { id }),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async updateVideo(
        id: VideoId,
        payload: UpdateVideoRequest,
    ): Promise<Result<Video, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('update_video', { id, payload }),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async updateRestoreVideo(
        id: VideoId,
    ): Promise<Result<Video, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('update_restore_video', { id }),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async updateAudio(
        id: AudioId,
        payload: UpdateAudioRequest,
    ): Promise<Result<Audio, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('update_audio', { id, payload }),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async updateRestoreAudio(
        id: AudioId,
    ): Promise<Result<Audio, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('update_restore_audio', { id }),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async updateSnippet(
        id: SnippetId,
        payload: UpdateSnippetRequest,
    ): Promise<Result<Snippet, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('update_snippet', { id, payload }),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async updateRestoreSnippet(
        id: SnippetId,
    ): Promise<Result<Snippet, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('update_restore_snippet', { id }),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async updateTag(
        id: TagId,
        payload: UpdateTagRequest,
    ): Promise<Result<Tag, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('update_tag', { id, payload }),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async updateSettings(
        payload: UpdateSettingsRequest,
    ): Promise<Result<Setting, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('update_settings', { payload }),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async utilSyncData(): Promise<Result<null, CommandError>> {
        try {
            return { status: 'ok', data: await TAURI_INVOKE('util_sync_data') };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async utilDropFiles(
        paths: string[],
    ): Promise<Result<number, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('util_drop_files', { paths }),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async utilCopyImage(id: ImageId): Promise<Result<Image, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('util_copy_image', { id }),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async utilCopyVideo(id: VideoId): Promise<Result<Video, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('util_copy_video', { id }),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async utilCopyAudio(id: AudioId): Promise<Result<Audio, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('util_copy_audio', { id }),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async utilCopySnippet(
        id: SnippetId,
    ): Promise<Result<Snippet, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('util_copy_snippet', { id }),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
};

/** user-defined events **/

export const events = __makeEvents__<{
    fileProcessingProgress: FileProcessingProgress;
}>({
    fileProcessingProgress: 'file-processing-progress',
});

/** user-defined constants **/

/** user-defined types **/

export type Audio = {
    id: AudioId;
    title: string | null;
    description: string | null;
    externalLink: string | null;
    useCounter: number;
    lastUsedAt: Timestamp | null;
    filePath: string;
    fileName: string;
    mimeType: string;
    fileSize: number;
    checksum: string;
    duration: number;
    isFavorite: boolean;
    tags: Tag[];
    deletedAt: Timestamp | null;
    createdAt: Timestamp;
};
export type AudioId = string;
export type CommandError =
    | { kind: 'Database'; message: string }
    | { kind: 'Io'; message: string }
    | { kind: 'Clipboard'; message: string }
    | { kind: 'Unknown'; message: string };
export type CreateSnippetRequest = {
    title: string | null;
    description: string | null;
    content: string;
    externalLink: string | null;
    tagIds: TagId[];
};
export type CreateTagRequest = { name: string };
export type DeleteRequest = { permanent?: boolean | null };
export type FileProcessingProgress = { current: number; total: number };
export type GeneralStats = {
    imageCount: number;
    videoCount: number;
    audioCount: number;
    snippetCount: number;
    tagCount: number;
};
export type Image = {
    id: ImageId;
    title: string | null;
    description: string | null;
    externalLink: string | null;
    useCounter: number;
    lastUsedAt: Timestamp | null;
    filePath: string;
    fileName: string;
    mimeType: string;
    fileSize: number;
    checksum: string;
    width: number;
    height: number;
    isFavorite: boolean;
    blurHash: string;
    tags: Tag[];
    deletedAt: Timestamp | null;
    createdAt: Timestamp;
};
export type ImageId = string;
export type Setting = {
    id: number;
    minimizeOnCopy: boolean;
    defaultVolume: number | null;
};
export type Snippet = {
    id: SnippetId;
    title: string | null;
    description: string | null;
    content: string;
    externalLink: string | null;
    useCounter: number;
    lastUsedAt: Timestamp | null;
    isFavorite: boolean;
    tags: Tag[];
    deletedAt: Timestamp | null;
    createdAt: Timestamp;
};
export type SnippetId = string;
export type Tag = { id: TagId; name: string; createdAt: Timestamp };
export type TagId = string;
export type Timestamp = number;
export type UpdateAudioRequest = {
    title: string | null;
    description: string | null;
    externalLink: string | null;
    isFavorite: boolean;
    useCounter: number;
    tagIds?: TagId[] | null;
};
export type UpdateImageRequest = {
    title: string | null;
    description: string | null;
    externalLink: string | null;
    isFavorite: boolean;
    useCounter: number;
    tagIds?: TagId[] | null;
};
export type UpdateSettingsRequest = {
    minimizeOnCopy?: boolean | null;
    defaultVolume?: number | null;
};
export type UpdateSnippetRequest = {
    title: string | null;
    description: string | null;
    externalLink: string | null;
    content: string;
    isFavorite: boolean;
    useCounter: number;
    tagIds?: TagId[] | null;
};
export type UpdateTagRequest = { name?: string | null };
export type UpdateVideoRequest = {
    title: string | null;
    description: string | null;
    externalLink: string | null;
    isFavorite: boolean;
    useCounter: number;
    tagIds?: TagId[] | null;
};
export type Video = {
    id: VideoId;
    title: string | null;
    description: string | null;
    externalLink: string | null;
    useCounter: number;
    lastUsedAt: Timestamp | null;
    filePath: string;
    fileName: string;
    mimeType: string;
    fileSize: number;
    checksum: string;
    hasAudio: boolean;
    duration: number;
    isFavorite: boolean;
    tags: Tag[];
    deletedAt: Timestamp | null;
    createdAt: Timestamp;
};
export type VideoId = string;

/** tauri-specta globals **/

import {
    invoke as TAURI_INVOKE,
    Channel as TAURI_CHANNEL,
} from '@tauri-apps/api/core';
import * as TAURI_API_EVENT from '@tauri-apps/api/event';
import { type WebviewWindow as __WebviewWindow__ } from '@tauri-apps/api/webviewWindow';

type __EventObj__<T> = {
    listen: (
        cb: TAURI_API_EVENT.EventCallback<T>,
    ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
    once: (
        cb: TAURI_API_EVENT.EventCallback<T>,
    ) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
    emit: null extends T
        ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
        : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
    | { status: 'ok'; data: T }
    | { status: 'error'; error: E };

function __makeEvents__<T extends Record<string, any>>(
    mappings: Record<keyof T, string>,
) {
    return new Proxy(
        {} as unknown as {
            [K in keyof T]: __EventObj__<T[K]> & {
                (handle: __WebviewWindow__): __EventObj__<T[K]>;
            };
        },
        {
            get: (_, event) => {
                const name = mappings[event as keyof T];

                return new Proxy((() => {}) as any, {
                    apply: (_, __, [window]: [__WebviewWindow__]) => ({
                        listen: (arg: any) => window.listen(name, arg),
                        once: (arg: any) => window.once(name, arg),
                        emit: (arg: any) => window.emit(name, arg),
                    }),
                    get: (_, command: keyof __EventObj__<any>) => {
                        switch (command) {
                            case 'listen':
                                return (arg: any) =>
                                    TAURI_API_EVENT.listen(name, arg);
                            case 'once':
                                return (arg: any) =>
                                    TAURI_API_EVENT.once(name, arg);
                            case 'emit':
                                return (arg: any) =>
                                    TAURI_API_EVENT.emit(name, arg);
                        }
                    },
                });
            },
        },
    );
}
