/** biome-ignore-all lint: Auto generate */
/** biome-ignore-all assist/source/organizeImports: Auto generate */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
    async getImages(): Promise<Result<Image[], CommandError>> {
        try {
            return { status: 'ok', data: await TAURI_INVOKE('get_images') };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async getVideos(): Promise<Result<Video[], CommandError>> {
        try {
            return { status: 'ok', data: await TAURI_INVOKE('get_videos') };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async getAudio(): Promise<Result<Audio[], CommandError>> {
        try {
            return { status: 'ok', data: await TAURI_INVOKE('get_audio') };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async getSnippets(): Promise<Result<Snippet[], CommandError>> {
        try {
            return { status: 'ok', data: await TAURI_INVOKE('get_snippets') };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async getTags(): Promise<Result<Tag[], CommandError>> {
        try {
            return { status: 'ok', data: await TAURI_INVOKE('get_tags') };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async getSettings(): Promise<Result<Setting, CommandError>> {
        try {
            return { status: 'ok', data: await TAURI_INVOKE('get_settings') };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async getGeneralStats(): Promise<Result<GeneralStats, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('get_general_stats'),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async utilDropFiles(
        paths: string[],
    ): Promise<Result<number, CommandError>> {
        try {
            return {
                status: 'ok',
                data: await TAURI_INVOKE('util_drop_files', { paths }),
            };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
};

/** user-defined events **/

/** user-defined constants **/

/** user-defined types **/

export type Audio = {
    id: string;
    title: string | null;
    description: string | null;
    externalLink: string | null;
    useCounter: number;
    lastUsedAt: Timestamp | null;
    filePath: string;
    mimeType: string;
    fileSize: number;
    checksum: string;
    duration: number;
    isFavorite: boolean;
    tags: Tag[];
    deletedAt: Timestamp | null;
    createdAt: Timestamp;
};
export type CommandError =
    | { kind: 'Database'; message: string }
    | { kind: 'Io'; message: string }
    | { kind: 'Unknown'; message: string };
export type GeneralStats = {
    imageCount: number;
    videoCount: number;
    audioCount: number;
    snippetCount: number;
    tagCount: number;
};
export type Image = {
    id: string;
    title: string | null;
    description: string | null;
    externalLink: string | null;
    useCounter: number;
    lastUsedAt: Timestamp | null;
    filePath: string;
    mimeType: string;
    fileSize: number;
    checksum: string;
    width: number;
    height: number;
    isFavorite: boolean;
    blurHash: string;
    tags: Tag[];
    deletedAt: Timestamp | null;
    createdAt: Timestamp;
};
export type Setting = { id: number; minimizeOnCopy: boolean };
export type Snippet = {
    id: string;
    title: string | null;
    description: string | null;
    content: string;
    externalLink: string | null;
    useCounter: number;
    lastUsedAt: Timestamp | null;
    isFavorite: boolean;
    tags: Tag[];
    deletedAt: Timestamp | null;
    createdAt: Timestamp;
};
export type Tag = { id: string; name: string; createdAt: Timestamp };
export type Timestamp = number;
export type Video = {
    id: string;
    title: string | null;
    description: string | null;
    externalLink: string | null;
    useCounter: number;
    lastUsedAt: Timestamp | null;
    filePath: string;
    mimeType: string;
    fileSize: number;
    checksum: string;
    hasAudio: boolean;
    duration: number;
    isFavorite: boolean;
    tags: Tag[];
    deletedAt: Timestamp | null;
    createdAt: Timestamp;
};

/** tauri-specta globals **/

import {
    invoke as TAURI_INVOKE,
    Channel as TAURI_CHANNEL,
} from '@tauri-apps/api/core';
import * as TAURI_API_EVENT from '@tauri-apps/api/event';
import { type WebviewWindow as __WebviewWindow__ } from '@tauri-apps/api/webviewWindow';

type __EventObj__<T> = {
    listen: (
        cb: TAURI_API_EVENT.EventCallback<T>,
    ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
    once: (
        cb: TAURI_API_EVENT.EventCallback<T>,
    ) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
    emit: null extends T
        ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
        : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
    | { status: 'ok'; data: T }
    | { status: 'error'; error: E };

function __makeEvents__<T extends Record<string, any>>(
    mappings: Record<keyof T, string>,
) {
    return new Proxy(
        {} as unknown as {
            [K in keyof T]: __EventObj__<T[K]> & {
                (handle: __WebviewWindow__): __EventObj__<T[K]>;
            };
        },
        {
            get: (_, event) => {
                const name = mappings[event as keyof T];

                return new Proxy((() => {}) as any, {
                    apply: (_, __, [window]: [__WebviewWindow__]) => ({
                        listen: (arg: any) => window.listen(name, arg),
                        once: (arg: any) => window.once(name, arg),
                        emit: (arg: any) => window.emit(name, arg),
                    }),
                    get: (_, command: keyof __EventObj__<any>) => {
                        switch (command) {
                            case 'listen':
                                return (arg: any) =>
                                    TAURI_API_EVENT.listen(name, arg);
                            case 'once':
                                return (arg: any) =>
                                    TAURI_API_EVENT.once(name, arg);
                            case 'emit':
                                return (arg: any) =>
                                    TAURI_API_EVENT.emit(name, arg);
                        }
                    },
                });
            },
        },
    );
}
