// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps, type VoidComponent } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Media
 * ```
 *          ░▒▒▒     ░▒▒▒
 *       ░▒▓█▓██  ░▒▓█▓██
 *    ░▒▓█▓▒░ ██▒▓█▓▒░ ██
 *   ▓██▓░    ███▓░    ██
 *    ░▒▓█▓▒░ ██▒▓█▓▒░ ██
 *       ░▒▓█▓██  ░▒▓█▓██
 *          ░▒▒▒     ░▒▒▒
 * ```
 */
export const IconMediaRewind: VoidComponent<IconProps> = (props) => {
    const [local, others] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Media Rewind'
            width={local.size || '1rem'}
            height={local.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...others}
        >
            <path
                d='M12 12L21 17V7L12 12ZM12 12V7L3 12L12 17V12Z'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
