// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps, type VoidComponent } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Media
 * ```
 *                  ░░
 *                  ▒█▓░
 *   ▒▓▓▓▓▓▒▒░  ░▒▒▓▓███▒
 *   ░░░░░░▒▓█▒ ▒▓▒▒▒██▓░
 *           ▒█▒    ▒▓░
 *            ██
 *            ▒█▒   ▒▓░
 *   ░░░░░▒▒▓▒ ▒█▓▒░▒██▓░
 *   ▒▓▓▓▓▓▒▒░  ░▒▒▓▓███▒
 *                  ▒█▓░
 *                  ░░
 * ```
 */
export const IconMediaShuffle: VoidComponent<IconProps> = (props) => {
    const [local, others] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Media Shuffle'
            width={local.size || '1rem'}
            height={local.size || '1rem'}
            viewBox='0 0 24 24'
            fill='none'
            {...others}
        >
            <path
                d='M18 20L21 17M21 17L18 14M21 17H17C14.2386 17 12 14.7614 12 12C12 9.23858 9.76142 7 7 7H3M18 4L21 7M21 7L18 10M21 7L17 7C15.8744 7 14.8357 7.37194 14 7.99963M3 17H7C8.12561 17 9.16434 16.6277 10 16'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
